# Codecov Configuration

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
        target: 75%
        threshold: 5%
    patch:
      default:
        target: 70%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
